/*remove duplicate rows*/

WITH CTE([Sale Date]
      ,[Loyalty]
      ,[Reciept Id]
      ,[Customer ID]
      ,[Customer First Name]
      ,[Customer Surname]
      ,[Staff ID]
      ,[Staff First Name]
      ,[Staff Surname]
      ,[Staff office]
      ,[Office Location]
      ,[Reciept Transaction Row ID]
      ,[Item ID]
      ,[Item Description]
      ,[Item Quantity]
      ,[Item Price]
      ,[Row Total], 
    duplicatecount)
AS (SELECT [Sale Date]
      ,[Loyalty]
      ,[Reciept Id]
      ,[Customer ID]
      ,[Customer First Name]
      ,[Customer Surname]
      ,[Staff ID]
      ,[Staff First Name]
      ,[Staff Surname]
      ,[Staff office]
      ,[Office Location]
      ,[Reciept Transaction Row ID]
      ,[Item ID]
      ,[Item Description]
      ,[Item Quantity]
      ,[Item Price]
      ,[Row Total], 
           ROW_NUMBER() OVER(PARTITION BY [Sale Date]
      ,[Loyalty]
      ,[Reciept Id]
      ,[Customer ID]
      ,[Customer First Name]
      ,[Customer Surname]
      ,[Staff ID]
      ,[Staff First Name]
      ,[Staff Surname]
      ,[Staff office]
      ,[Office Location]
      ,[Reciept Transaction Row ID]
      ,[Item ID]
      ,[Item Description]
      ,[Item Quantity]
      ,[Item Price]
      ,[Row Total]
           ORDER BY [Reciept Id]) AS DuplicateCount
    FROM [dbo].[DataStaging])
delete FROM CTE
WHERE DuplicateCount > 1;
